---
# tasks file for diffie-hellmann

- name: Install diffie-hellmann packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ diffie_hellmann_packages }}"
    - "{{ diffie_hellmann_additional_packages }}"
  tags:
    - package
    - diffie-hellmann

- name: Generating Diffie-Hellmann pems
  shell: "openssl gendh -out /etc/ssl/dh_{{ item }}.pem -2 {{ item }}"
  args:
    creates: "/etc/ssl/dh_{{ item }}.pem"
  with_items:
    - "{{ diffie_hellmann_strength }}"
  tags:
    - config
    - diffie-hellmann
    - skip_ansible_lint
