---
version: 2
jobs:
  build:

    docker:
      - image: docker:stable

    working_directory: ~/repo

    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - checkout:
          path: ~/repo

      - run:
          name: "Install tools"
          command: "apk add --update python python-dev py-pip build-base
                    openssl-dev libffi-dev linux-headers"

      - run:
          # this can be removed
          name: Locate site Packages
          command: python -c "import site; print(site.getsitepackages())"

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: "Install python dependencies"
          command: "pip install -r requirements.txt"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: "run tests"
          command: "molecule test"
